import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router'
import Alert from '../../components/Alert.jsx'
import Button from '../../components/Button.jsx'
import FormField from '../../components/FormField.jsx'
import Loading from '../../components/Loading.jsx'
import PageHeader from '../../components/PageHeader.jsx'
import { useAuth } from '../../auth/useAuth.js'
import { api, getErrorMessage } from '../../lib/api.js'
import { displayName } from '../../lib/roles.js'

// Account numbers are generated by sp_open_account: "DB" + 3-digit branch + 7-digit id.
const ACCOUNT_NUMBER = /^DB\d{4,}$/i

export default function DashboardPage() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [overview, setOverview] = useState(null)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')

  useEffect(() => {
    let ignore = false
    api
      .get('/api/v1/staff/overview')
      .then(({ data }) => !ignore && setOverview(data.data))
      .catch((err) => !ignore && setError(getErrorMessage(err)))
    return () => {
      ignore = true
    }
  }, [])

  function handleSearch(event) {
    event.preventDefault()
    const q = query.trim()
    if (!q) return
    if (ACCOUNT_NUMBER.test(q)) {
      navigate(`/staff/accounts/${q.toUpperCase()}`)
    } else {
      navigate(`/staff/customers?tab=all&search=${encodeURIComponent(q)}`)
    }
  }

  const customers = overview?.customers

  return (
    <section>
      <PageHeader title={`Welcome, ${displayName(user)}`} description="Customers, accounts and cash at your branch." />

      <form onSubmit={handleSearch} className="mb-6 flex flex-col gap-3 rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:flex-row sm:items-end">
        <FormField
          id="quick-search"
          label="Find an account or customer"
          type="search"
          className="flex-1"
          hint="An account number (e.g. DB0010000001) opens the account; anything else searches customers by name, ID, phone, email or username."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <Button type="submit" className="sm:mb-6">
          Search
        </Button>
      </form>

      {error ? (
        <Alert>{error}</Alert>
      ) : !customers ? (
        <Loading />
      ) : (
        <>
          {customers.PENDING > 0 && (
            <Link
              to="/staff/customers?tab=pending"
              className="mb-4 flex items-center justify-between gap-4 rounded-xl bg-amber-50 p-4 text-amber-900 ring-1 ring-amber-200 hover:bg-amber-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-600"
            >
              <span className="font-medium">
                {customers.PENDING} {customers.PENDING === 1 ? 'customer' : 'customers'} awaiting KYC
              </span>
              <span className="text-sm font-semibold">Review →</span>
            </Link>
          )}
          <div className="grid gap-4 sm:grid-cols-3">
            <Stat label="Awaiting KYC" value={customers.PENDING} to="/staff/customers?tab=pending" />
            <Stat label="Verified" value={customers.VERIFIED} to="/staff/customers?tab=verified" />
            <Stat label="Rejected" value={customers.REJECTED} to="/staff/customers?tab=rejected" />
          </div>
        </>
      )}
    </section>
  )
}

function Stat({ label, value, to }) {
  return (
    <Link
      to={to}
      className="block rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 hover:ring-navy-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-navy-600"
    >
      <p className="text-sm text-slate-500">{label}</p>
      <p className="mt-1 text-3xl font-semibold tabular-nums text-navy-900">{value}</p>
    </Link>
  )
}
